version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: urna-eletronica-app
    ports:
      - "3001:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: urna-db
    restart: always
    tty: true
    environment:
      - POSTGRES_DB=urna-eletronica
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
 dbdata:
